<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
    public function getTicketsNumber($dateVisit)
        {
            return $this
                ->createQueryBuilder('t')
                ->innerJoin('t.commande', 'c')
                ->select('COUNT(t)')
                ->where ('c.dateVisit = :dateVisit')
                ->setParameter('dateVisit', $dateVisit)
                ->getQuery()
                ->getSingleScalarResult()
           ;
        }

}
