# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.validator.limitTickets:
        class: AppBundle\Validator\LimitTicketsValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name:validator.constraint_validator, alias:app_limitTickets }

    app.commande.manager:
        class: AppBundle\Manager\CommandeManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

