# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.validator.limitTickets:
        class: AppBundle\Validator\LimitTicketsValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name:validator.constraint_validator, alias:app_limitTickets }
